upstream:
  default:
    - tcp-tls:8.8.4.4
    - https://8.8.4.4/dns-query
    - tcp-tls:8.8.8.8
    - https://8.8.8.8/dns-query
    - tcp-tls:dns.google
    - https://dns.google/dns-query
    - tcp-tls:9.9.9.10
    - https://9.9.9.10/dns-query
    - https://dns10.quad9.net/dns-query
    - tcp-tls:101.101.101.101
    - https://101.101.101.101/dns-query
    - https://dns.twnic.tw/dns-query
    - tcp-tls:1.1.1.1
    - https://1.1.1.1/dns-query
    - tcp-tls:1.0.0.1
    - https://1.0.0.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://mozilla.cloudflare-dns.com/dns-query
    - tcp-tls:dns.nextdns.io
    - https://dns.nextdns.io
    - tcp-tls:anycast.dns.nextdns.io
    - https://anycast.dns.nextdns.io
    - https://firefox.dns.nextdns.io
    - tcp-tls:open.dns0.eu
    - https://open.dns0.eu/dns-query
    - tcp-tls:dns0.eu
    - https://dns0.eu/dns-query
    - tcp-tls:p0.freedns.controld.com
    - https://freedns.controld.com/p0
    - tcp-tls:uncensored.freedns.controld.com
    - https://freedns.controld.com/uncensored
    - tcp-tls:private.canadianshield.cira.ca
    - https://private.canadianshield.cira.ca/dns-query
    - tcp-tls:max.rethinkdns.com
    - https://max.rethinkdns.com
    - tcp-tls:uncensored.dns.dnswarden.com
    - https://dns.dnswarden.com/uncensored
    - tcp-tls:dns-unfiltered.adguard.com
    - https://dns-unfiltered.adguard.com/dns-query
    - tcp-tls:doh.mullvad.net
    - https://doh.mullvad.net/dns-query
    - tcp-tls:dns.surfshark.com
    - https://dns.surfshark.com/dns-query
    - tcp-tls:dns.switch.ch
    - https://dns.switch.ch/dns-query
    - tcp-tls:dns.dnshome.de
    - https://dns.dnshome.de/dns-query
    - tcp-tls:security-filter-dns.cleanbrowsing.org
    - https://doh.cleanbrowsing.org/doh/security-filter/
    - tcp-tls:dot1.applied-privacy.net
    - https://doh.applied-privacy.net/query
    - tcp-tls:dns.digitale-gesellschaft.ch
    - https://dns.digitale-gesellschaft.ch/dns-query
    - tcp-tls:dns.digitalsize.net
    - https://dns.digitalsize.net/dns-query
    - tcp-tls:unicast.uncensoreddns.org
    - https://unicast.uncensoreddns.org/dns-query
    - tcp-tls:anycast.uncensoreddns.org
    - https://anycast.uncensoreddns.org/dns-query
    - tcp-tls:dot.libredns.gr
    - https://doh.libredns.gr/dns-query
    - tcp-tls:dot.seby.io
    - https://doh.seby.io:8443/dns-query
    - https://doh-2.seby.io/dns-query
    - tcp-tls:getdnsapi.net
    - https://dns.hinet.net/dns-query
    - https://ordns.he.net/dns-query
    - tcp-tls:dns.hostux.net
    - https://dns.hostux.net/dns-query
    - tcp-tls:puredns.org
    - https://puredns.org/dns-query
    - tcp-tls:www.morbitzer.de
    - https://www.morbitzer.de/dns-query
    - tcp-tls:ns1.opennameserver.org
    - https://ns1.opennameserver.org/dns-query
    - tcp-tls:ns2.opennameserver.org
    - https://ns2.opennameserver.org/dns-query
    - tcp-tls:ns3.opennameserver.org
    - https://ns3.opennameserver.org/dns-query
    - tcp-tls:ns4.opennameserver.org
    - https://ns4.opennameserver.org/dns-query
    - https://opennic1.eth-services.de:853/
    - https://opennic2.eth-services.de:853/
    - https://pluton.plan9-dns.com/dns-query
    - https://helios.plan9-dns.com/dns-query
    - https://kronos.plan9-dns.com/dns-query
    - https://sby-doh.limotelu.org/dns-query
    - https://chewbacca.meganerd.nl/dns-query
    - https://secure.avastdns.com/dns-query
    - https://dnsnl.alekberg.net/dns-query
    - https://dnsse.alekberg.net/dns-query
    - https://ns1.flodns.net/dns-query
    - https://ns2.flodns.net/dns-query
    - tcp-tls:dns.neutopia.org
bootstrapDns:
  - upstream: https://dns.quad9.net/dns-query
    ips:
      - 9.9.9.9
      - 149.112.112.112
  - upstream: https://dns.google/dns-query
    ips:
      - 8.8.8.8
      - 8.8.4.4
  - upstream: https://1.1.1.1/dns-query
    ips:
      - 1.1.1.1
      - 1.0.0.1  
connectIPVersion: v4

# optional: use black and white lists to block queries (for example ads, trackers, adult pages etc.)
blocking:
  processingConcurrency: 1
  # definition of blacklist groups. Can be external link (http/https) or local file
  blackLists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/fake.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/tif.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/personal.txt
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Scam
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Cryptocurrency
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Typo
    #  - https://raw.githubusercontent.com/ChathuraJW/my_pihole_addlists/main/addlists/complete_addlist_tick.txt
    #  - https://raw.githubusercontent.com/m0zgen/dns-hole/master/dns-blacklist.txt
    #  - https://raw.githubusercontent.com/m0zgen/dns-hole/master/malisious.txt
# definition of whitelist groups. Attention: if the same group has black and whitelists, whitelists will be used to disable particular blacklist entries. If a group has only whitelist entries -> this means only domains from this list are allowed, all other domains will be blocked
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Whitelists/Whitelist
      - https://raw.githubusercontent.com/m0zgen/bld-agregator/data/allowlist.txt
     # - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
     # - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist-referral.txt
      - https://raw.githubusercontent.com/KEINOS/BlockList/main/whitelist.txt
      - https://raw.githubusercontent.com/PeterDaveHello/url-shorteners/master/list
  # definition: which groups should be applied for which client
  clientGroupsBlock:
    # default will be used, if no special definition for a client name exists
    default:
      - ads
  blockType: zeroIp
  # optional: TTL for answers to blocked domains
  # default: 6h
  blockTTL: 1m
  # optional: automatically list refresh period (in duration format). Default: 4h.
  # Negative value -> deactivate automatically refresh.
  # 0 value -> use default
  refreshPeriod: 4h
  # optional: timeout for list download (each url). Default: 60s. Use large values for big lists or slow internet connections
  downloadTimeout: 15m
  # optional: Download attempt timeout. Default: 60s
  downloadAttempts: 5
  # optional: Time between the download attempts. Default: 1s
  downloadCooldown: 10s
  # optional: if failOnError, application startup will fail if at least one list can't be downloaded / opened. Default: blocking
  startStrategy: fast
caching:
  # duration how long a response must be cached (min value).
  # If <=0, use response's TTL, if >0 use this value, if TTL is smaller
  # Default: 0
  minTime: 5m
  # duration how long a response must be cached (max value).
  # If <0, do not cache responses
  # If 0, use TTL
  # If > 0, use this value, if TTL is greater
  # Default: 0
  maxTime: 24h
  # Max number of cache entries (responses) to be kept in cache (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  maxItemsCount: 20000
  # if true, will preload DNS results for often used queries (default: names queried more than 5 times in a 2-hour time window)
  # this improves the response time for often used queries, but significantly increases external traffic
  # default: false
  prefetching: true
  # prefetch track time window (in duration format)
  # default: 120
  prefetchExpires: 2h
  # name queries threshold for prefetch
  # default: 5
  prefetchThreshold: 3
  # Max number of domains to be kept in cache for prefetching (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  prefetchMaxItemsCount: 10000
  # Time how long negative results (NXDOMAIN response or empty result) are cached. A value of -1 will disable caching for negative results.
  # Default: 30m
  cacheTimeNegative: 30m
  
log:
  level: warn
  privacy: true

ports:
  # optional: DNS listener port(s) and bind ip address(es), default 53 (UDP and TCP). Example: 53, :53, "127.0.0.1:5353,[::1]:5353"
  dns: 3000
  # optional: Port(s) and optional bind ip address(es) to serve HTTP used for prometheus metrics, pprof, REST API, DoH... If you wish to specify a specific IP, you can do so such as 192.168.0.1:4000. Example: 4000, :4000, 127.0.0.1:4000,[::1]:4000
  http: 8100
