upstream:
  default:
    - tcp-tls:8.8.4.4
    - https://8.8.4.4/dns-query
    - tcp-tls:8.8.8.8
    - https://8.8.8.8/dns-query
    - tcp-tls:dns.google
    - https://dns.google/dns-query
    - tcp-tls:9.9.9.10
    - https://9.9.9.10/dns-query
    - https://dns10.quad9.net/dns-query
    - tcp-tls:1.1.1.1
    - https://1.1.1.1/dns-query
    - tcp-tls:1.0.0.1
    - https://1.0.0.1/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://mozilla.cloudflare-dns.com/dns-query
    - tcp-tls:open.dns0.eu
    - https://open.dns0.eu/dns-query
    - https://dns.dnswarden.com/uncensored
    - tcp-tls:ordns.he.net
    - https://ordns.he.net/dns-query
    

    
bootstrapDns:
  - upstream: https://dns.quad9.net/dns-query
    ips:
      - 9.9.9.9
      - 149.112.112.112
  - upstream: https://dns.google/dns-query
    ips:
      - 8.8.8.8
      - 8.8.4.4
  - upstream: https://1.1.1.1/dns-query
    ips:
      - 1.1.1.1
      - 1.0.0.1  
connectIPVersion: v4

blocking:
  processingConcurrency: 1
  blackLists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/pro.txt
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Scam
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Malware
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Cryptocurrency
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Ads
      - https://github.com/shahidcodes/firebog-ticked-list/releases/latest/download/ads.txt
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Whitelists/Whitelist
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      - https://raw.githubusercontent.com/dnswarden/blocklist-staging/main/whitelist/tinylist.txt
      - https://raw.githubusercontent.com/dnswarden/blocklist-staging/main/whitelist/whitelistcommon.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist.txt
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIp
  blockTTL: 10m
  refreshPeriod: 24h
  downloadTimeout: 5m
  downloadAttempts: 2
  downloadCooldown: 10s
  startStrategy: fast
  maxErrorsPerFile: 500
caching:
  minTime: 5m
  maxTime: 72h
  maxItemsCount: 10000
  prefetching: true
  prefetchExpires: 4h
  prefetchThreshold: 5
  prefetchMaxItemsCount: 2000
  cacheTimeNegative: 30m
  
log:
  level: warn
  privacy: true

ports:
  dns: 3000
  http: 8100
