upstream:
  default:
    - https://open.dns0.eu/dns-query
    - https://anycast.dns2.nextdns.io/dns-query
bootstrapDns:
  - tcp+udp:1.1.1.1
  - tcp+udp:8.8.8.8
  - tcp+udp:9.9.9.9
  - https://1.1.1.1/dns-query
  - upstream: https://dns.google/dns-query
    ips:
      - 8.8.8.8
connectIPVersion: v4

# optional: use black and white lists to block queries (for example ads, trackers, adult pages etc.)
blocking:
  processingConcurrency: 8
  # definition of blacklist groups. Can be external link (http/https) or local file
  blackLists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/multi.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/fake.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/tif.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/personal.txt
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Scam
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Cryptocurrency
      - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Typo
    #  - https://raw.githubusercontent.com/ChathuraJW/my_pihole_addlists/main/addlists/complete_addlist_tick.txt
    #  - https://raw.githubusercontent.com/m0zgen/dns-hole/master/dns-blacklist.txt
    #  - https://raw.githubusercontent.com/m0zgen/dns-hole/master/malisious.txt
# definition of whitelist groups. Attention: if the same group has black and whitelists, whitelists will be used to disable particular blacklist entries. If a group has only whitelist entries -> this means only domains from this list are allowed, all other domains will be blocked
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/m0zgen/dns-hole/master/whitelist.txt
    #  - https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Whitelists/Whitelist
      - https://raw.githubusercontent.com/m0zgen/bld-agregator/data/allowlist.txt
     # - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
     # - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt
      #- https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist.txt
      #- https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist-referral.txt
      #- https://raw.githubusercontent.com/KEINOS/BlockList/main/whitelist.txt
  # definition: which groups should be applied for which client
  clientGroupsBlock:
    # default will be used, if no special definition for a client name exists
    default:
      - ads
  blockType: zeroIp
  # optional: TTL for answers to blocked domains
  # default: 6h
  blockTTL: 5m
  # optional: automatically list refresh period (in duration format). Default: 4h.
  # Negative value -> deactivate automatically refresh.
  # 0 value -> use default
  refreshPeriod: 24h
  # optional: timeout for list download (each url). Default: 60s. Use large values for big lists or slow internet connections
  downloadTimeout: 30s
  # optional: Download attempt timeout. Default: 60s
  downloadAttempts: 3
  # optional: Time between the download attempts. Default: 1s
  downloadCooldown: 10s
  # optional: if failOnError, application startup will fail if at least one list can't be downloaded / opened. Default: blocking
  startStrategy: fast
caching:
  # duration how long a response must be cached (min value).
  # If <=0, use response's TTL, if >0 use this value, if TTL is smaller
  # Default: 0
  minTime: 5m
  # duration how long a response must be cached (max value).
  # If <0, do not cache responses
  # If 0, use TTL
  # If > 0, use this value, if TTL is greater
  # Default: 0
  maxTime: 24h
  # Max number of cache entries (responses) to be kept in cache (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  maxItemsCount: 5000
  # if true, will preload DNS results for often used queries (default: names queried more than 5 times in a 2-hour time window)
  # this improves the response time for often used queries, but significantly increases external traffic
  # default: false
  prefetching: true
  # prefetch track time window (in duration format)
  # default: 120
  prefetchExpires: 2h
  # name queries threshold for prefetch
  # default: 5
  prefetchThreshold: 5
  # Max number of domains to be kept in cache for prefetching (soft limit). Useful on systems with limited amount of RAM.
  # Default (0): unlimited
  prefetchMaxItemsCount: 1000
  # Time how long negative results (NXDOMAIN response or empty result) are cached. A value of -1 will disable caching for negative results.
  # Default: 30m
  cacheTimeNegative: 30m

log:
  # optional: Log level (one from debug, info, warn, error). Default: info
  level: error
ports:
  # optional: DNS listener port(s) and bind ip address(es), default 53 (UDP and TCP). Example: 53, :53, "127.0.0.1:5353,[::1]:5353"
  dns: 3000
  # optional: Port(s) and optional bind ip address(es) to serve HTTPS used for prometheus metrics, pprof, REST API, DoH... If you wish to specify a specific IP, you can do so such as 192.168.0.1:443. Example: 443, :443, 127.0.0.1:443,[::1]:443
  http: $PORT
